[config]
default_to_workspace = true

#
#
# RUN BACKFILL & SERVER
#
#

[tasks.backfill]
script = "cargo run -r -p backfill"

[tasks.epoch]
script = "cargo run -r -p epoch"

#
#
# POSTGRES SETUP
#
#

# install postgresql cli to create database instance and superuser on MacOS
[tasks.install_postgresql_macos]
script = "brew install postgresql@13"
# start postgres server
[tasks.start_postgresql_macos]
script = "brew services start postgresql@13"

# isntall postgresql cli to create database instance and superuser on Linux
[tasks.install_postgresql_linux]
script = "sudo apt install postgresql postgresql-contrib"
# start postgres server
[tasks.start_postgresql_linux]
script = "sudo systemctl start postgresql && sudo systemctl enable postgresql"

# sqlx is a manager to connect to a postgres database. It does not create a server or users!
[tasks.install_sqlx_cli]
command = "cargo"
args = ["install", "sqlx-cli", "--no-default-features", "--features", "native-tls,postgres"]

[tasks.recreate_database]
dependencies = ["install_sqlx_cli"]
env = { DATABASE_URL = "postgres://postgres:password@localhost:5432/epoch" }
script = "echo 'y' | sqlx database drop && sqlx database create"

[tasks.wipe_migrations]
script = "rm -rf migrations"

[tasks.copy_migrations]
script = "chmod +x ./copy.sh && ./copy.sh"

[tasks.revert_database]
dependencies = ["install_sqlx_cli"]
env = { DATABASE_URL = "postgres://postgres:password@localhost:5432/epoch" }
script = "sqlx migrate revert"

[tasks.create_migrations]
dependencies = ["install_sqlx_cli"]
env = { DATABASE_URL = "postgres://postgres:password@localhost:5432/epoch" }
command = "sqlx"
args = ["migrate", "add", "-r", "epoch"]

[tasks.migrate_database]
dependencies = ["install_sqlx_cli"]
env = { DATABASE_URL = "postgres://postgres:password@localhost:5432/epoch" }
script = "sqlx migrate run"

[tasks.update_database]
dependencies = ["create_database", "migrate_database"]

[tasks.init_database]
dependencies = ["wipe_migrations", "create_database", "create_migrations", "copy_migrations", "migrate_database"]

