[toolchain]
# Check https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html
# for valid toolchains.
channel = "1.75.0"
#channel = "nightly-2023-03-22"
component = ["cargo-sort", "clippy"]
