// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

use crate::tables::SpacetimeAccount;
#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct SendAccountArgs {
    pub account: SpacetimeAccount,
}

impl Reducer for SendAccountArgs {
    const REDUCER_NAME: &'static str = "send_account";
}

#[allow(unused)]
pub fn send_account(account: SpacetimeAccount) {
    SendAccountArgs { account }.invoke();
}

#[allow(unused)]
pub fn on_send_account(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &SpacetimeAccount) + Send + 'static,
) -> ReducerCallbackId<SendAccountArgs> {
    SendAccountArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let SendAccountArgs { account } = __args;
        __callback(__identity, __addr, __status, account);
    })
}

#[allow(unused)]
pub fn once_on_send_account(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &SpacetimeAccount) + Send + 'static,
) -> ReducerCallbackId<SendAccountArgs> {
    SendAccountArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let SendAccountArgs { account } = __args;
        __callback(__identity, __addr, __status, account);
    })
}

#[allow(unused)]
pub fn remove_on_send_account(id: ReducerCallbackId<SendAccountArgs>) {
    SendAccountArgs::remove_on_reducer(id);
}
